name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      uses: Azure/docker-login@v1
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/AzureRegistryGitActions:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/AzureRegistryGitActions:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/AzureRegistryGitActions:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/AzureRegistryGitActions
